### ISSUE TITLE
RPI3 buffer warning/make error. 

### ISSUE THREAD

**Issue by spacehelpplease** [nasa/cFS#206]
```
/home/pi/Desktop/sat/cFS/cfe/fsw/cfe-core/src/sb/cfe_sb_buf.c: In function ‘CFE_SB_GetBufferFromPool’:
/home/pi/Desktop/sat/cFS/cfe/fsw/cfe-core/src/sb/cfe_sb_buf.c:94:21: error: cast increases required alignment of target type [-Werror=cast-align]
     bd->Buffer    = (CFE_SB_Buffer_t *)address;
                     ^
cc1: all warnings being treated as errors
```

given its just a warning I tried to suppress it with the ol' `make -k`

and this pops

```
make[6]: Target 'all' not remade because of errors.
make[5]: *** [Makefile:141: all] Error 2
make[4]: *** [CMakeFiles/native_default_cpu1-all.dir/build.make:57: CMakeFiles/native_default_cpu1-all] Error 2
make[4]: Target 'CMakeFiles/native_default_cpu1-all.dir/build' not remade because of errors.
make[3]: *** [CMakeFiles/Makefile2:298: CMakeFiles/native_default_cpu1-all.dir/all] Error 2
make[3]: Target 'CMakeFiles/mission-all.dir/all' not remade because of errors.
make[2]: *** [CMakeFiles/Makefile2:177: CMakeFiles/mission-all.dir/rule] Error 2
make[2]: Target 'mission-all' not remade because of errors.
make[1]: *** [Makefile:214: mission-all] Error 2
make: *** [Makefile:120: all] Error 2
```

Trying to compile on raspberry OS with a RPI 3B works on ubuntu 18.04 following the same steps. 

any help is appreciated tried main and integration-candidate  

new to git sorry if i missed anything,.

**Comment by jphickey** [comment]
Yeah `make -k` only keeps building other non-dependencies.  What you want is to either remove `-Werror` from your local build options, or change `-Wcast-align` to `-Wno-cast-align`.

Also Note - This warning should be fixed in the next cycle (e.g. PR nasa/cfe#1197), so unless you are in a hurry, you could just pull `main` branch again in a few days.
